
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obfufvpbajnqmrinhmqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZnVmdnBiYWpucW1yaW5obXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzUxMzksImV4cCI6MjA2MTY1MTEzOX0.qQZ_gyI9DJ27KM0ASS96yHahXPF3vep4hacyUALKq-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
